# Generated by Django 4.2.11 on 2024-03-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
