# Generated by Django 4.2.11 on 2024-03-25 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0004_chat_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_data',
            name='likes',
            field=models.ManyToManyField(related_name='liked_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
