# Generated by Django 4.2.11 on 2024-03-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_chat_data_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
